# -*- coding: utf-8 -*-

RISK_FREE_INTEREST_RATE = 4.0 / 100.0;
INFLATION_RATE = 6.0 / 100.0;
RISK_INTEREST_RATE = RISK_FREE_INTEREST_RATE + INFLATION_RATE;

SLEEP_TIME_OUT = 0.5

#Stock Type
STOCK_TYPE_BLACK = -1
STOCK_TYPE_NONE = 0
STOCK_TYPE_FAVORITE = 1

# Rating Type:
POOR_TYPE = -1
PRICE_TYPE = 1 << 0
LIABILITIES_TYPE = 1 << 1
GROWTH_TYPE = 1 << 2

# Analyze period:
GROWTH_YEAR_MIN = 3
TIME_TO_MARKET_YEAR_MIN = 5

# Checkout threshold
BOOK_VALUE_PER_SHARE_MIN = 1

PE_MAX = 20
PB_MAX = 2
ROE_MAX = 30

SEASONS_IN_A_YEAR = 4

DATE_FORMAT = "%Y-%m-%d"
DATE_TIME_FORMAT = "%Y-%m-%d %H:%M"

DAY = "day"
WEEK = "week"
MONTH = "month"

DATA_PATH = "./data/"
DATA_FINANCIAL_PATH = DATA_PATH + "financial" + "/"
DATA_SHARE_BONUS_PATH = DATA_PATH + "share_bonus" + "/"
DATA_STOCK_PATH = DATA_PATH + "stock" + "/"
DATA_STOCK_DAY_PATH = DATA_STOCK_PATH + DAY + "/"
DATA_STOCK_WEEK_PATH = DATA_STOCK_PATH + WEEK + "/"
DATA_STOCK_MONTH_PATH = DATA_STOCK_PATH + MONTH + "/"
